name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths_ignore:
      - .github/actions/setup-python/action.yml
      - .github/workflows/release.yml
      - .github/workflows/auto-merge.yml
      - .github/workflows/ruff.yml
  pull_request:
    branches:
      - main
    paths_ignore:
      - .github/actions/setup-python/action.yml
      - .github/workflows/release.yml
      - .github/workflows/auto-merge.yml
      - .github/workflows/ruff.yml
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Github Registry
      uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GIT_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=edge,value=nightly
          type=sha,event=branch
          type=ref,event=tag
          type=ref,event=pr

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
